## Invoke time function

POST https://serveless-portal.azurewebsites.net/admin/functions/TimerFunction HTTP/1.1
x-functions-key: AcJFtb2IZg3QN3mQyMwLB3NyXk0XYoytVDBUL5EueVbrWMhZBbJlBg==
Content-Type: "application/json"

{
    
}